id = "gitingest"
name = "Git Ingest"
description = "A powerful Zed extension that allows you to browse and analyze Git repositories via slash commands."
version = "0.1.0"
schema_version = 1
authors = ["Víctor García"]
repository = "https://github.com/gc-victor/gitingest"

[slash_commands.gitingest]
description = "Browse and analyze Git repositories"
requires_argument = true
tooltip_text = "Ask Perplexity"